# Generated by Django 3.0.4 on 2020-04-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upweekly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='author',
        ),
        migrations.RemoveField(
            model_name='week',
            name='date',
        ),
    ]
