# Generated by Django 3.0.4 on 2020-04-21 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upweekly', '0002_auto_20200420_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 2, 9, 46, 400764, tzinfo=utc)),
        ),
    ]
