# Generated by Django 3.0.4 on 2020-04-21 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upweekly', '0003_auto_20200420_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 15, 34, 28, 536482, tzinfo=utc)),
        ),
    ]
